name: Setup Runner
description: Installs required technologies on the runner

inputs:
  techs:
    description: List of technologies and versions (e.g., "java:11, python:3.11, node")
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/install.sh
        ${{ github.action_path }}/install.sh "${{ inputs.techs }}"
      shell: bash
